import React, { useState } from 'react';
import { Grid, Button, Typography, Box, TextField } from '@mui/material';
import ReactQuill from 'react-quill';
import 'react-quill/dist/quill.snow.css'; // Import styles for React Quill

const CounterApp = () => {
  const [count, setCount] = useState(0);
  const [text, setText] = useState('');
  const [name, setName] = useState('');
  const [userId, setUserId] = useState(Math.floor(Math.random() * 10000));
  const [address, setAddress] = useState('');
  const [phone, setPhone] = useState('');
  const [email, setEmail] = useState('');

  const increment = () => setCount(count + 1);
  const decrement = () => setCount(count - 1);
  const reset = () => setCount(0);

  const handleSave = () => {
    if (!name || !address || !phone || !email) {
      alert("Please fill in all the fields.");
      return;
    }

    const userData = { userId, name, address, phone, email };
    localStorage.setItem("userData", JSON.stringify(userData));
    console.log("User data saved:", userData);
  };

  return (
    <Grid container spacing={2} style={{ height: '100vh', padding: '20px' }}>
      
      {/* Counter Section */}
      <Grid item xs={6}>
        <Box 
          border={1} 
          borderRadius={2} 
          padding={3} 
          textAlign="center"
          style={{ 
            background: `linear-gradient(to top, darkgrey ${count * 10}%, violet)`, 
            transition: 'background 0.5s ease-in-out',
            height: '230px' // Slightly decreased height
          }}
        >
          <Typography variant="h4" style={{ color: 'white' }}>{count}</Typography>
          <Typography variant="h6" style={{ marginBottom: '10px', color: 'white' }}>Counter</Typography>
          <Grid container justifyContent="center" spacing={2}>
            <Grid item>
              <Button variant="contained" color="primary" onClick={increment}>+</Button>
            </Grid>
            <Grid item>
              <Button variant="outlined" color="error" onClick={reset}>Reset</Button>
            </Grid>
            <Grid item>
              <Button variant="contained" color="secondary" onClick={decrement}>-</Button>
            </Grid>
          </Grid>
        </Box>
      </Grid>

      {/* Top Right Section - Rich Text Editor */}
      <Grid item xs={6}>
        <Box border={1} borderRadius={2} padding={2} height="240px"> {/* Adjusted height */}
          <Typography variant="h6" style={{ marginBottom: '10px' }}>Rich Text Editor</Typography>
          <ReactQuill value={text} onChange={setText} style={{ height: '150px' }} /> {/* Adjusted editor height */}
        </Box>
      </Grid>

      {/* UserData JSON Object - Adjusted Input Fields */}
      <Grid item xs={6}>
        <Box border={1} borderRadius={2} padding={2.5} height="250px">
          <Typography variant="h6">UserData JSON Object</Typography>
          <TextField 
            label="Name" 
            variant="outlined" 
            fullWidth 
            size="medium" 
            margin="normal"
            InputProps={{ style: { height: '50px' } }} // Adjusted height
            value={name} 
            onChange={(e) => setName(e.target.value)}
          />
          <TextField 
            label="ID (Autogenerated)" 
            variant="outlined" 
            fullWidth 
            size="medium"
            margin="normal"
            InputProps={{ style: { height: '50px' } }} // Adjusted height
            value={userId} 
            disabled
          />
          <Button 
            variant="contained" 
            color="primary" 
            fullWidth 
            style={{ marginTop: '10px' }} // Spacing for better fit
            onClick={handleSave}
          >
            Save
          </Button>
        </Box>
      </Grid>

      {/* User Profile Section */}
      <Grid item xs={6}>
        <Box border={1} borderRadius={2} padding={2.5} height="250px">
          <Typography variant="h6">User Data</Typography>
          <TextField 
            label="Address" 
            variant="outlined" 
            fullWidth 
            size="small"
            margin="dense"
            value={address} 
            onChange={(e) => setAddress(e.target.value)}
          />
          <TextField 
            label="Phone Number" 
            variant="outlined" 
            fullWidth 
            size="small"
            margin="dense"
            value={phone} 
            onChange={(e) => setPhone(e.target.value)}
          />
          <TextField 
            label="Email" 
            variant="outlined" 
            fullWidth 
            size="small"
            margin="dense"
            value={email} 
            onChange={(e) => setEmail(e.target.value)}
          />
          <Button 
            variant="contained" 
            color="secondary" 
            fullWidth 
            style={{ marginTop: '10px' }} // Added margin to fit button inside
            onClick={handleSave}
          >
            Save
          </Button>
        </Box>
      </Grid>
      
    </Grid>
  );
};

export default CounterApp;
